repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
    - id: copy-readme
      name: copy-readme
      entry: python precommit/copy-readme.py
      files: (^README.md$|^docs/index.md$)
      language: system
      fail_fast: true
    - id: flake8
      name: flake8
      entry: flake8
      args: ['src', 'test']
      language: system
      pass_filenames: false
    - id: mypy
      name: mypy
      entry: mypy
      args: ['src', 'test']
      language: system
      pass_filenames: false
    - id: pytest
      name: pytest
      entry: pytest
      args: ['--no-cov']
      language: system
      pass_filenames: false
