site_name: Interleave Playlist
site_url: https://example.com # TODO: Change this!!
repo_url: https://github.com/tsweeney256/interleave_playlist
theme: readthedocs
nav:
  - Interleave Playlist:
    - Overview: index.md
  - Input File:
    - Scopes:
      - Hierarchy: input/scope/scope-hierarchy.md
      - Global: input/scope/global-scope.md
      - Location: input/scope/location-scope.md
      - Group: input/scope/group-scope.md
    - Options:
      - Blacklist & Whitelist: input/option/blackwhitelist.md
      - Regex: input/option/regex.md
      - Priority: input/option/priority.md
      - Weight: input/option/weight.md
      - Timed: input/option/timed.md
